import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import Provide from '../components/Provide'
import Statics from '../components/Statics'
import Advantages from '../components/Advantages'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Whats from '../components/Whats'
import Map from '../components/Map'
import { AfterPurchase } from '../components/AfterPurchase'
import Guarantee from '../components/Guarantee'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Valley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='direction-rtl'>
        <Navbar/>
        <Hero/>
        <Slider/>
        <Statics/>
        <Provide/>
        <Guarantee/>
        <Advantages/>
        <AfterPurchase/>
        <Map/>
        <Footer/>
        <Whats/>
      </main>

      
    </div>
  )
}
